#!/bin/bash
#
# Deploy mathtoys.org to Netlify from the ~/src/publish area.

PUB=~/src/publish

run() {
  echo '$' $@
  "$@"
}

echo ==== Publishing from $PUB/prooftoys ====
sleep 3

run cd $PUB/prooftoys
run git pull

run cd $PUB/mathtoys
run git pull

run netlify deploy --site mathtoys.netlify.app --dir site -p
